### ISSUE TITLE
Frontend Roadmap

### ISSUE THREAD

**Issue by MadsFrost** [Voxtir/voxtir#145]
# Roadmap for Frontend
1. General frontend bug(s) fix and browser / file support testing.
- [ ] Modal's not behaving correctly with scroll and overflow
- [ ] More toasts for error handling or user feedback.
- [ ] Fixup email templates to have a background.
- [ ] General bug fixes.
- [ ] Data/policy new user information modal to only show until accepted.

2. Document Editor trackbar with speaker(s) showing on it's own track:
- [ ] Trackbar for actual track.
- [ ] Track for speaker(n) showing color for when the speaker is with-in a range of time on track.

3. User on-boarding or showcase of features.
4. Additional nice-to-haves:
- [ ] New speaker paragraph component for more structured audit.
- [ ] GPT-4 Summary of interview small corrections in grammatics.
- [ ] Premium feature to be based on which model to use, where initially free-tier on small and medium (@gustavhartz ?)
