### ISSUE TITLE
Pre-release TODO

### ISSUE THREAD

**Issue by MadsFrost** [Voxtir/voxtir#67]
- [x] Add document functionality to documents page.
- [x] Edit document functionality to documents page.
- [x] Empty documents page view
- [ ] Implement list of recent visited documents in nav.
- [ ] Show NON allowed entry to document error (Nice to have)
- [x] Share project
